Update install

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -87,6 +87,8 @@ clear
 
 proot-distro login altaera
 clear
+if [ -d /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/altaera ]
+then
 echo "**********INSTALLATION COMPLETED**********
 " | sed  -e :a -e "s/^.\{1,$(tput cols)\}$/ & /;ta" | tr -d '\n' | head -c $(tput cols);
 echo "________________________________________________________________
@@ -99,6 +101,52 @@ echo "
 - To start, please type in 'ae'."
 echo "________________________________________________________________
 " | sed  -e :a -e "s/^.\{1,$(tput cols)\}$/ & /;ta" | tr -d '\n' | head -c $(tput cols);
+else
+dialog --title "AltaeraAI - PRoot Distro installation failure" --msgbox 'There were problems installing the PRoot Distro environment. This can happen, for instance, when some of the mirror servers are down, therefore unable to retrieve some necessary files. In the next step, you will be asked whether to retry PRoot Distro environment installation, or to cancel.' 40 80
+
+#!/bin/bash
+
+dialog --title "PRoot Distro installation failure" \
+        --backtitle "AltaeraAI - Installation" \
+        --yesno "Would you like to retry the PRoot Distro environment installation?" 7 60
+
+response=$?
+case $response in
+
+        0)      
+        clear
+        1) exit
+        255) exit
+esac
+
+echo "The PRoot Distro environment failed to install. Retrying in 5 seconds...
+
+[to cancel, press Ctrl+C]
+"
+echo "10..."
+sleep 1
+echo "9..."
+sleep 1
+echo "8..."
+sleep 1
+echo "7..."
+sleep 1
+echo "6..."
+sleep 1
+echo "5..."
+sleep 1
+
+clear
+
+rm -rf '/data/data/com.termux/files/home/altaera_install_pt-2.sh'
+rm -rf '/data/data/com.termux/files/home/altaera_install_pt-3.sh'
+rm -rf '/data/data/com.termux/files/home/altaera_install_pt-4.sh'
+rm -rf '/data/data/com.termux/files/home/altaera-install_method.sh'
+wget https://raw.githubusercontent.com/ThinkThroughLabs/AltaeraAI/main/scripts/altaera-install_method.sh -q --show-progress
+chmod a+x 'altaera-install_method.sh'
+bash 'altaera-install_method.sh'
+clear
+proot-distro install altaera
 ;;
 
          2)
